spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            provider: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ "profile_nickname", "account_email" ]
          naver:
            provider: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ "name", "email" ]

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: false   # 운영에서는 보통 Off (또는 IP 제한)

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:"https://your-frontend.example.com"}

jwt:
  secret: ${JWT_SECRET}  # 운영은 반드시 환경변수/Secret Manager 사용
